# spectre-insights/docker-compose.yml

version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=http://backend:5000/api
      - NUXT_PUBLIC_STRAPI_URL=http://strapi:1337
    depends_on:
      - backend
      - strapi

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/spectre_insights
      - JWT_SECRET=your_jwt_secret
      - STRAPI_API_URL=http://strapi:1337
      - EMAIL_SERVICE=SendGrid
      - EMAIL_USER=your_sendgrid_username
      - EMAIL_PASS=your_sendgrid_password
      - NODE_ENV=development
    depends_on:
      - mongo
      - strapi

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  strapi:
    image: strapi/strapi:latest
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: spectre_insights
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      NODE_ENV: development
    depends_on:
      - mongo
    volumes:
      - strapi-data:/srv/app

volumes:
  mongo-data:
  strapi-data:
